# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: ascvd 0.0.1 ruby lib

Gem::Specification.new do |s|
  s.name = "ascvd"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Zipnosis, Inc."]
  s.date = "2015-12-08"
  s.description = "ASCVD 10-year and lifetime risk calculator"
  s.email = "developers@zipnosis.com.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "ascvd.gemspec",
    "lib/ascvd.rb",
    "lib/ascvd/calculator.rb",
    "lib/ascvd/lifetime_calculator.rb",
    "lib/ascvd/ten_year_calculator.rb",
    "lib/ascvd/value.rb",
    "lib/ascvd/value/age_value.rb",
    "lib/ascvd/value/boolean_value.rb",
    "lib/ascvd/value/bptreatment_value.rb",
    "lib/ascvd/value/cholesterol_value.rb",
    "lib/ascvd/value/diabetes_value.rb",
    "lib/ascvd/value/hdl_value.rb",
    "lib/ascvd/value/race_value.rb",
    "lib/ascvd/value/range_value.rb",
    "lib/ascvd/value/sex_value.rb",
    "lib/ascvd/value/smoker_value.rb",
    "lib/ascvd/value/systolic_value.rb",
    "lib/ascvd/value/value_list_value.rb",
    "spec/lib/ascvd/calculator_spec.rb",
    "spec/lib/ascvd/value/age_value_spec.rb",
    "spec/lib/ascvd/value/boolean_value_spec.rb",
    "spec/lib/ascvd/value/bptreatment_value_spec.rb",
    "spec/lib/ascvd/value/cholesterol_value_spec.rb",
    "spec/lib/ascvd/value/diabetes_value_spec.rb",
    "spec/lib/ascvd/value/hdl_value_spec.rb",
    "spec/lib/ascvd/value/race_value_spec.rb",
    "spec/lib/ascvd/value/sex_value_spec.rb",
    "spec/lib/ascvd/value/smoker_value_spec.rb",
    "spec/lib/ascvd/value/systolic_value_spec.rb",
    "spec/lib/ascvd/value_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/zipnosis/ascvd"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.8"
  s.summary = "ASCVD 10-year and lifetime risk calculator"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<pry>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<pry>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<pry>, [">= 0"])
  end
end

